language: rust
branches:
  only:
  - master
install:
- true
script:
- true
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  cargo install --git https://github.com/rust-lang-nursery/mdBook.git &&
  mdbook build &&
  sudo pip install ghp-import &&
  ghp-import -n book &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
env:
  global:
  - secure: WbBTORJ41B8303Ue/evU6TVQYDRoyAz8cgUIyTMgksUKwRpdJKFf4I3UbTBdHG1sIcNKQTjPDgMzgyVc3F2ys8jm2QtHioMBFHaJQ5UDH6ugu7hQjwlGcep/ijTq4IwwSg/+uUo1wk/sLeNaThNn2cCwBfMx1aWsA6B0wUUB7hQoaaLSRWO+JhbGnO8ycQ8+/iI7reusGHZH4K6KDsEqs0aABcJ6hottRqgYT7TdTdWxIZvR6v4Rgm7Eyk/t8AG3oMHe04MoP3wUaS9vOVoE4qrVu+MCgJQk6goD63OrXIxSXjz0JloR5Gy3PY/U2JuIU4s6+3shrcCykjrA/NenVnO5yxJ0Dd/jCbhZTfYYiegNLu20jLb574fjkNub21FuDAV9eqjgjSelNcaZbAk5pDVuqxku2qoSi4l4EKJwO/P6RVJayBudT3dHgE9S7qCL29OQVrH52aYq3A8qWcyPMMzQgLaz4pWAJGP9egIKlGU4yPnin0siWp5XXHd8Xnz/foCu02bnBuwPB0RRl51zfg4ErVXwQsdx4d4SHtfWZy5p0vZCOaC9q8/rOg1XFsoT/PTgqcNP4BAmkzoB2tDGzqhVESOfQPwrsz6dLdfEbffuSbSFMjLyZFFolMYea9VBorsI8Ji538BIScgnqqT6+W0bNuidCWK3gV2rxu3J7vY=
  - secure: P2TkwOYrxxoSsQk2hcTHqg+0RvQApOajk1W/vEhozy707wb6XS11NMk3zQKdjsFwk/vnd09+GIIPLOOpMYoqtI+yiiiBQWeL1lMs2yJArlc3dJxt2pmwpCgznibl4xSe54je+Q2Y83+pmebRMY3H+H8qRUP17BMJzEn0gNPzPhJzKgcLR4ZqHygmWw8A8qMEpDgofZ9TFPLLN1fbu/VGQwa11JoqEvB0lMRCRnndksOzSjrIs37kR+Oect6dZd+hwa2zqSb0xA575wXT4Ozt7P8mw3Qmf87E/ZAIO1dGzU74/Ai9IbFnMVnNxRrsdO2/LGrRH0UJHSbmaMm7EUe/WfGnj87nvyCKUytP5168Z9NP1kjxjSoYAQ+p2BANwyxEOx0gau7p4zVcOWskPuJwy83ej0e1dLG5Tt0hviTOOCyDw86pOQ02seN11okZvY9vnwzJNTrySrPlqFS7cYW2bzE+kSTn7KSUhpm2vLgORGxAnc9BYfshj5Mqm0kzVbGZKcgxTtkTSWeBfMKDk0Fd4HFDIlQKY+jAq0QSQoROS+zcbIsZbyV0oFhZ7H/K+xooQU91pOvVv5wjF+z9Qj/y5a4mOSda8ueBYtvxqs1a25YocZzf1m0AqGr56hpcSXEyEgj1X82syA+iVF/p4Z+ewQqgdfL3XEdl/t/SEOy7NUE=
